<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="mayank" name="testcases.TutorMysessionTest" tests="3" failures="1" timestamp="03 May 2018 05:24:09 GMT" time="77.486" errors="0">
  <testcase name="TutorMysess" time="31.112" classname="testcases.TutorMysessionTest"/>
  <testcase name="TutorMysess" time="31.224" classname="testcases.TutorMysessionTest"/>
  <testcase name="TutorMysess" time="15.150" classname="testcases.TutorMysessionTest">
    <failure type="java.lang.AssertionError" message="There is no booking in pending from tutor expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: There is no booking in pending from tutor expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at pages.TutorMysessionPage.MySession(Unknown Source)at testcases.TutorMysessionTest.TutorMysess(Unknown Source)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.TestNG.privateMain(TestNG.java:1330)at org.testng.TestNG.main(TestNG.java:1299)]]>
    </failure>
  </testcase> <!-- TutorMysess -->
</testsuite> <!-- testcases.TutorMysessionTest -->
